import * as T from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';

export type Mode = 'menu' | 'playing' | 'paused' | 'over';
export type Action = 'left' | 'right' | 'up' | 'down';
export type Stats = { distance: number; coins: number; time: number; score: number };
type Item = { mesh: T.Group; type: string; lane: number; laneX: number; checked: boolean };
type Particle = { mesh: T.Mesh; velocity: T.Vector3; life: number };
const clamp = T.MathUtils.clamp;

export class RunnerGame {
  renderer: T.WebGLRenderer;
  scene = new T.Scene();
  camera = new T.PerspectiveCamera(47, 1, .3, 180);
  mode: Mode = 'menu';
  sound = false;
  stats: Stats = { distance: 0, coins: 0, time: 0, score: 0 };
  onStats: (s: Stats) => void;
  onOver: (s: Stats) => void;
  onToast: (text: string) => void;
  private host: HTMLElement;
  private resizeObserver: ResizeObserver;
  private audio?: AudioContext;
  private runner = new T.Group();
  private hips = new T.Bone();
  private spine = new T.Bone();
  private legs: { thigh: T.Bone; knee: T.Bone }[] = [];
  private arms: { shoulder: T.Bone; elbow: T.Bone }[] = [];
  private tiles!: T.InstancedMesh;
  private slab!: T.InstancedMesh;
  private curbs!: T.InstancedMesh;
  private columns: T.Object3D[] = [];
  private plants: T.Object3D[] = [];
  private items: Item[] = [];
  private pool = new Map<string, T.Group[]>();
  private prototypes = new Map<string, T.Group>();
  private particles: Particle[] = [];
  private dummy = new T.Object3D();
  private lane = 0;
  private jump = 0;
  private jumpVelocity = 0;
  private slideTime = 0;
  private duck = 0;
  private groundY = 0;
  private travel = 0;
  private phase = 0;
  private last = 0;
  private accumulator = 0;
  private spawnAt = 0;
  private row = 0;
  private shake = 0;
  private hudTick = 0;
  private menuOffset = .205;
  private width = 1;
  private height = 1;
  private bend = 0;
  private bendTarget = 0;
  private bendTimer = 10;
  private gateAt = 60;
  private templeGroup?: T.Group;
  private marble: T.MeshStandardMaterial;
  private stone = new T.MeshStandardMaterial({ color: '#e2d4bc', roughness: .91 });
  private trim = new T.MeshStandardMaterial({ color: '#f5e8d1', roughness: .82 });
  private blue = new T.MeshStandardMaterial({ color: '#38309e', roughness: .35, metalness: .25 });
  private blueLight = new T.MeshStandardMaterial({ color: '#b2a1fc', emissive: '#6350b8', emissiveIntensity: .12, roughness: .38 });
  private sphereGeo = new T.SphereGeometry(1, 16, 12);
  private boxGeo = new T.BoxGeometry(1, 1, 1);
  private particleGeo = new T.OctahedronGeometry(.07);
  private particleMaterial = new T.MeshBasicMaterial({ color: '#8d78df' });
  private dustMaterial = new T.MeshBasicMaterial({ color: '#f5e7cd' });
  private resources: T.Object3D[] = [];

  constructor(host: HTMLElement, onStats: (s: Stats) => void, onOver: (s: Stats) => void, onToast: (t: string) => void) {
    this.host = host; this.onStats = onStats; this.onOver = onOver; this.onToast = onToast;
    this.renderer = new T.WebGLRenderer({ antialias: true, alpha: false, powerPreference: 'high-performance' });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.6));
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = T.PCFSoftShadowMap;
    this.renderer.toneMapping = T.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.2;